# Generated by Django 2.2.26 on 2022-01-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restuarant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('free', 'Free'), ('asian', 'Asian'), ('french', 'French')], max_length=30, null=True)),
            ],
        ),
    ]
